version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports: ["6333:6333"]
    volumes:
      - qdrant-data:/qdrant/storage

  a2a:
    build: .
    image: workshop-builder:latest
    command: >
      python -m uvicorn a2a_universal.server:app
      --host 0.0.0.0 --port 8000
    environment:
      A2A_ENABLE_KNOWLEDGE: "1"
      A2A_VDB: "qdrant"
      A2A_QDRANT_URL: "http://qdrant:6333"
      A2A_PORT: "8000"
      # Embeddings (override with .env)
      A2A_EMBEDDINGS_PROVIDER: "${A2A_EMBEDDINGS_PROVIDER:-watsonx}"
      A2A_EMBEDDINGS_MODEL: "${A2A_EMBEDDINGS_MODEL:-ibm/slate-125m-english-rtrvr}"
      WATSONX_API_KEY: "${WATSONX_API_KEY:-}"
      WATSONX_URL: "${WATSONX_URL:-https://us-south.ml.cloud.ibm.com}"
      WATSONX_PROJECT_ID: "${WATSONX_PROJECT_ID:-}"
      OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
    depends_on: [qdrant]
    ports: ["8000:8000"]
    env_file: [.env]

  web:
    build: .
    image: workshop-builder:latest
    command: >
      gunicorn app:app -b 0.0.0.0:5000 -w 2 -k gthread --threads 8 --timeout 120
    environment:
      FLASK_HOST: "0.0.0.0"
      FLASK_PORT: "5000"
      A2A_BASE: "http://a2a:8000"
    depends_on: [a2a]
    ports: ["5000:5000"]
    env_file: [.env]

volumes:
  qdrant-data:
