version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    env_file:
      - ../.env
    environment:
      REDIS_URL: redis://redis:6379/0
      STATIC_ROOT: /app/ui/dist
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    command: python -m workers.worker
    env_file:
      - ../.env
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
