version: 1
formatters:
  default:
    format: "%(asctime)s %(levelname)s %(name)s [%(threadName)s] %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
loggers:
  a2a:
    level: INFO
    handlers: [console]
    propagate: false
  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: false
root:
  level: INFO
  handlers: [console]
